package anniversaire

import java.security.MessageDigest
import javax.xml.bind.DatatypeConverter
import javax.crypto.Cipher
import javax.crypto.spec.SecretKeySpec
import java.util.Base64

object LocalEncryption {
  def sha256(input: String): String = {
    val digest = MessageDigest.getInstance("SHA-256")
    val hash = digest.digest(input.getBytes("UTF-8"))
    DatatypeConverter.printHexBinary(hash).toLowerCase()
  }

  def main(args: Array[String]): Unit = {
    // Use the list of tokens generated by the generateToken function
    val words = List(
      "foo",
      "bar"
    )

    // Generate a list of hashes from the list of tokens
    val hashes = words.map(word => sha256(word))

    // Print the list of hashes
    println("\nList of SHA-256 hashes:")
    println("[")
    hashes.foreach(hash => println(s"  \"$hash\","))
    println("]")

    // Also print the total count
    println(s"\nTotal number of hashes: ${hashes.length}")
  }
}

// Provide a list of funny words; and let it generate a list of 200 tokens (with a prefix) containing 3 random words from the list
// def generateToken() = {
//   val words = List(
//     "foobar"
//   )
//   List
//     .fill(200)(
//       "myprefix-" + util.Random.shuffle(words).take(3).mkString("-")
//     )
//     .distinct
// }
