package anniversaire.resources

object Costumes {
  val costumesList: List[(String, String)] = List(
    ("Mario", "Luigi"),
    ("Astérix", "Obélix"),
    ("Roméo", "Juliette"),
    ("Ariel", "Polochon"),
    ("Tintin", "Milou"),
    ("Dupont", "Dupont"),
    ("Winnie", "Porcinet"),
    ("Sherlock", "Watson"),
    ("Dr Jekyll", "Mr Hyde"),
    ("Robinson", "Vendredi"),
    ("Princesse Leïa", "Han Solo"),
    ("Laurel", "Hardy"),
    ("Bonnie", "Clyde"),
    ("G. de Montmirail", "Jacquouille la Fripouille"),
    ("Tom", "Jerry"),
    ("Cléopatre", "César"),
    ("Batman", "Robin"),
    ("Père Noel", "Mère Noël"),
    ("Mr Smith", "Mrs Smith"),
    ("Leelou Dallas", "Corben Dallas"),
    ("Marge Simpson", "Homer Simpson"),
    ("Olive", "Tom"),
    ("Jeanne", "Serge"),
    ("Serena Williams", "Venus Williams"),
    ("Trump", "Melania"),
    ("Famille Addams", "Famille Adamas"),
    ("Aladdin", "Abu"),
    ("Titi", "Gros minet"),
    ("Adam", "Eve"),
    ("Jesus", "Marie"),
    ("Igor Bogdanoff", "Grichka Bogdanoff"),
    ("Bébé (dirty dancing)", "Johnny (dirty dancing)"),
    ("Vincent Vega", "Jules Winnfield"),
    ("Jack (titanic)", "Rose (titanic)"),
    ("Shrek", "La princesse de Shrek"),
    ("Sartre", "Beauvoir"),
    ("Popeye", "La femme de popeye"),
    ("Superman", "Superwoman"),
    ("118", "218"),
    ("Le petit chaperon rouge", "Le loup"),
    ("Cruella", "Un dalmatien"),
    ("Ou est charlie", "Charlène"),
    ("Ketchup", "Mayo"),
    ("Le bossu", "Esmeralda"),
    ("Strumpf", "Strumpfette"),
    ("Danny Zuko (Grease)", "Dandy Olsson (Grease)"),
    ("Harry Potter", "Hermione Granger"),
    ("Mitch", "Pamela"),
    ("Tomtom", "Nana"),
    ("Mickey", "Mini"),
    ("Ange", "Démon"),
    ("M&M bleu", "M&M rouge"),
    ("Lenon", "Mccartney"),
    ("César", "Brutus"),
    ("Thelma", "Louise"),
    ("Austin power", "La copine de Austin power"),
    ("Veronique", "Davina"),
  )

}
