package anniversaire.resources

object Costumes {
  val costumesList: List[(String, String)] = List(
    ("Mario", "Luigi"),
    ("Astérix", "Obélix"),
    ("César", "Brutus"),
    ("Gomez Addams", "Morticia Addamas"),
    ("Aladdin", "Jasmine"),
    ("Titi", "Gros minet"),
    ("Mitch", "Pamela"),
    ("Adam", "Eve"),
    ("Jesus", "Marie"),
    ("Roméo", "Juliette"),
    ("Popeye", "La femme de popeye"),
    ("Superman", "Superwoman"),
    ("118", "218"),
    ("Cruella", "Un dalmatien"),
    ("Ou est charlie", "Charlène"),
    ("Jack (titanic)", "Rose (titanic)"),
    ("Shrek", "La princesse de Shrek"),
    ("Ketchup", "Mayo"),
    ("Le bossu", "Esmeralda"),
    ("Schtroumpf", "Schtroumpfette"),
    ("Ange", "Démon"),
    ("Mickey", "Mini"),
    ("Harry Potter", "Hermione Granger"),
    ("Tintin", "Milou"),
    ("Dupont", "Dupont"),
    ("Winnie", "Porcinet"),
    ("M&M bleu", "M&M rouge"),
    ("Sherlock", "Watson"),
    ("Le petit chaperon rouge", "Le loup"),
    ("Ariel", "Polochon"),
    ("Trump", "Melania"),
    ("Marge Simpson", "Homer Simpson"),
    ("Tom", "Jerry"),
    ("Mr Smith", "Mrs Smith"),
    ("Minion", "Gru"),
    ("Blanche neige", "Un des 7 nains"),
    ("Princesse Leïa", "Han Solo"),
    ("Laurel", "Hardy"),
    ("Cléopatre", "César"),
    ("Batman", "Robin"),
    ("Père Noel", "Mère Noël"),
    ("Leelou Dallas", "Corben Dallas"),
    ("Dr Jekyll", "Mr Hyde"),
    ("Robinson", "Vendredi"),
    ("Serena Williams", "Venus Williams"),
    ("Bonnie", "Clyde"),
    ("Olive", "Tom"),
    ("Jeanne", "Serge"),
    ("G. de Montmirail", "Jacquouille la Fripouille"),
    ("Bébé (dirty dancing)", "Johnny"),
    ("Vincent Vega", "Jules Winnfield"),
    ("Sartre", "Beauvoir"),
    ("Danny Zuko", "Dandy Olsson (Grease)"),
    ("Tomtom", "Nana"),
    ("Lenon", "Mccartney"),
    ("Thelma", "Louise"),
    ("Austin power", "La copine de Austin power"),
    ("Veronique", "Davina"),
    ("Igor Bogdanoff", "Grichka Bogdanoff"),
    ("tic", "tac")
  )

}
