package anniversaire.resources
import anniversaire.Anniversaire.defaultToken

case class Guest(name: String, host: List[String], token: String)

object Guests {
  val guests: List[Guest] = List(
    Guest("glescornet@gmail.com",
          List("B"),
          "king-baguette-party-tente-banana"),
    Guest("sml.vgr@gmail.com",
          List("T"),
          "chocolat-queen-baguette-bene-banana"),
    Guest("quentinburban@laposte.net",
          List("F"),
          "baguette-birthday-love-france-tente"),
    Guest("marionmetivier86@gmail.com",
          List("F"),
          "birthday-tiphanie-banana-queen-fun"),
    Guest("Germain.marie@live.fr",
          List("B"),
          "king-tiphanie-france-party-gold"),
    Guest("Clemensbuschhoff@gmail.com",
          List("T"),
          "banana-chocolat-tente-bene-baguette"),
    Guest("mattattoo79@yahoo.de",
          List("T"),
          "chocolat-king-birthday-party-bene"),
    Guest("kris.neugebauer@googlemail.com",
          List("T"),
          "bene-baguette-fun-francois-tente"),
    Guest("laure.chabrolle@gmail.com",
          List("F"),
          "tiphanie-bene-francois-gold-banana"),
    Guest("lamberti.julien@gmail.com",
          List("F"),
          "birthday-king-bene-francois-queen"),
    Guest("theotime.tetu@gmail.com",
          List("F"),
          "party-tiphanie-banana-love-francois"),
    Guest("till.wohlfarth@faszinationeinrad.com",
          List("T"),
          "love-gold-chocolat-francois-party"),
    Guest("Elodie.thines@gmail.com", List("B"), "love-gold-party-fun-bene"),
    Guest("caro_chevalier@hotmail.fr",
          List("B"),
          "banana-fun-france-birthday-chocolat"),
    Guest("Gwenaelle.jolygj@gmail.com",
          List("F"),
          "birthday-bene-king-fun-france"),
    Guest("Quentin.fabulet@gmail.com",
          List("F"),
          "queen-fun-birthday-baguette-party"),
    Guest("juliette.laurence@gmail.com",
          List("B", "F"),
          "tente-francois-king-fun-tiphanie"),
    Guest("hug.burban@gmail.com", List("F"), "tente-fun-tiphanie-queen-gold"),
    Guest("boulanger.juli@gmail.com",
          List("T"),
          "king-tiphanie-fun-queen-party"),
    Guest("felixdietze@gmail.com",
          List("T"),
          "bene-chocolat-party-king-birthday"),
    Guest("Quentin.dumont59@gmail.com",
          List("T"),
          "banana-tente-gold-birthday-france"),
    Guest("mgx.barbier@gmail.com",
          List("T"),
          "bene-francois-birthday-baguette-france"),
    Guest("raphael.colleau@gmail.com",
          List("T"),
          "fun-birthday-gold-francois-party"),
    Guest("guillaume.axel.francois@hotmail.com",
          List("T"),
          "love-gold-tiphanie-francois-birthday"),
    Guest("creff.arthur@gmail.com",
          List("F"),
          "birthday-love-banana-gold-tente"),
    Guest("noelie.merlet@hotmail.fr",
          List("B,F"),
          "love-bene-gold-france-francois"),
    Guest("gregoireroux69@gmail.com",
          List("T"),
          "bene-francois-baguette-banana-france"),
    Guest("sandra.vagao@gmail.com",
          List("T"),
          "tente-tiphanie-bene-france-party"),
    Guest("Heygreg@hotmail.fr", List("T"), "party-chocolat-baguette-bene-love"),
    Guest("Maiw.cadoret@gmail.com",
          List("F"),
          "birthday-baguette-love-fun-gold"),
    Guest("alexraud@hotmail.com",
          List("F"),
          "gold-baguette-banana-francois-party"),
    Guest("lindsay.kibuey@gmail.com",
          List("F"),
          "baguette-bene-party-france-king"),
    Guest("rousselot.marie@orange.fr",
          List("T"),
          "baguette-king-queen-tiphanie-france"),
    Guest("yannick.richard@hotmail.fr",
          List("T"),
          "king-party-chocolat-queen-gold"),
    Guest("Lea.reyx@yahoo.fr", List("T"), "tente-bene-birthday-fun-love"),
    Guest("anais.rbt@gmail.com", List("T"), "love-bene-fun-tiphanie-chocolat"),
    Guest("Theophile.moreau@gmail.com",
          List("T, F"),
          "france-fun-queen-tiphanie-tente"),
    Guest("choutet.isabelle@gmail.com",
          List("F"),
          "gold-love-francois-king-france"),
    Guest("boris.beillevaire@gmail.com",
          List("F"),
          "chocolat-love-gold-banana-birthday"),
    Guest("sarah.beauvais@protonmail.com",
          List("F"),
          "love-birthday-king-queen-france"),
    Guest("aureliaguil@gmail.com",
          List("T"),
          "party-love-banana-chocolat-tiphanie"),
    Guest("Matthiasrock@hotmail.fr",
          List("T"),
          "francois-chocolat-birthday-fun-party"),
    Guest("Florence.gourdon@gmail.com",
          List("B"),
          "queen-tente-love-baguette-birthday"),
    Guest("Sayemoon@free.fr", List("B"), "chocolat-queen-bene-tente-fun"),
    Guest("stefano1.olivieri@gmail.com",
          List("T"),
          "chocolat-gold-france-bene-fun"),
    Guest("carole.legall89@gmail.com",
          List("T"),
          "love-baguette-queen-francois-birthday"),
    Guest("pierrel_claire@hotmail.com",
          List("B"),
          "banana-bene-fun-tiphanie-birthday"),
    Guest("gourdon_denis@yahoo.fr",
          List("B"),
          "bene-francois-king-tiphanie-chocolat"),
    Guest("sevmarion@hotmail.com",
          List("B"),
          "baguette-birthday-love-france-gold"),
    Guest("ronan.laurans@laposte.net",
          List("T"),
          "france-king-banana-fun-tente"),
    Guest("guerinlouise44@gmail.com",
          List("B"),
          "bene-tente-banana-gold-france"),
    Guest("juliennaud@me.com", List("B"), "gold-bene-baguette-party-francois"),
    Guest("valentineheraud@hotmail.fr",
          List("B"),
          "francois-tiphanie-france-chocolat-party"),
    Guest("gfrancois.mail@gmail.com",
          List("T"),
          "party-francois-fun-chocolat-france"),
    Guest("jjliguori@gmail.com",
          List("T"),
          "party-tiphanie-queen-chocolat-bene"),
    Guest("marioncle@hotmail.fr",
          List("B"),
          "party-tiphanie-bene-chocolat-birthday"),
    Guest("hugo.langlaisvignon@gmail.com",
          List("B"),
          "chocolat-fun-tente-bene-birthday"),
    Guest("sebastien.decreme@gmail.com",
          List("T"),
          "gold-birthday-baguette-party-francois"),
    Guest("marie.rpch@gmail.com",
          List("T"),
          "baguette-queen-birthday-gold-bene"),
    Guest("joel.mballa@gmail.com",
          List("T"),
          "birthday-king-baguette-francois-chocolat"),
    Guest("fabian-braun@mailbox.org",
          List("T"),
          "king-tiphanie-party-gold-baguette"),
    Guest("margaux.peneau@gmail.com",
          List("T"),
          "banana-gold-chocolat-baguette-party"),
    Guest("Florent.creutin@gmail.com",
          List("T"),
          "king-tente-fun-chocolat-banana"),
    Guest("didi.el.zein@gmail.com",
          List("B"),
          "party-tiphanie-love-queen-baguette"),
    Guest("mathias.peronne@gmail.com",
          List("B"),
          "baguette-france-banana-tente-fun"),
    Guest("champion.sophie@yahoo.com",
          List("B"),
          "francois-france-banana-tiphanie-queen"),
    Guest("laulotte44@hotmail.com",
          List("B"),
          "bene-party-france-queen-francois"),
    Guest("Michel-lebourdonnec@live.fr",
          List("B"),
          "bene-banana-love-tente-baguette"),
    Guest("youri.corbineau@gmail.com",
          List("B"),
          "queen-tente-france-party-birthday"),
    Guest("florent.quilichini@gmail.com",
          List("T"),
          "baguette-queen-birthday-france-banana"),
    Guest("aurelierolland@hotmail.fr",
          List("B"),
          "baguette-chocolat-love-francois-fun"),
    Guest("Guillaume.chopin@neuf.fr",
          List("T"),
          "tente-gold-birthday-banana-queen"),
    Guest("hamon.matthieu@gmail.com",
          List("B"),
          "banana-tiphanie-king-fun-birthday"),
    Guest("dimitri.fasquel@free.fr", List("B"), "gold-tente-queen-love-bene"),
    Guest("p.ganser@yahoo.de", List("T"), "king-baguette-banana-bene-fun"),
    Guest("letellier.avocat@laposte.net",
          List("B"),
          "banana-king-tiphanie-tente-fun"),
    Guest("martins.manon@gmail.com", List("T"), "queen-bene-francois-fun-king"),
    Guest("jeanromainsignorelli@gmail.com",
          List("F"),
          "chocolat-france-party-bene-queen"),
    Guest("lolaalfonzo@gmail.com", List("F"), "party-gold-banana-king-love"),
    Guest("marine.bertucchi@gmail.com",
          List("F"),
          "banana-love-tiphanie-francois-chocolat"),
    Guest("benjamin.reuche@gmail.com",
          List("B"),
          "francois-banana-party-chocolat-france"),
    Guest("eleonore.bondu@gmail.com",
          List("B"),
          "tente-chocolat-birthday-tiphanie-bene"),
    Guest("jeremydousset@gmail.com",
          List("T"),
          "francois-bene-banana-king-birthday"),
    Guest("g.muenkel@gmail.com",
          List("T"),
          "france-party-francois-chocolat-birthday"),
    Guest("lucie.rouland@gmail.com", List("B"), "party-love-fun-bene-tiphanie"),
    Guest("anthony-pacaud@laposte.net",
          List("T"),
          "party-king-birthday-banana-fun"),
    Guest("vivet.lucie@gmail.com",
          List("T"),
          "baguette-francois-king-france-party"),
    Guest("", List(""), defaultToken),
    Guest("dousset.guillaume@gmail.com",
          List("T"),
          "queen-banana-chocolat-bene-king"),
    Guest("jeremie.dubois56@gmail.com",
          List("F"),
          "birthday-banana-francois-gold-chocolat"),
    Guest("Deborah.jeune@gmail.com ",
          List("B"),
          "king-birthday-banana-gold-fun"),
    Guest("laure.kerfourn@gmail.com ",
          List("F"),
          "gold-bene-queen-birthday-banana"),
    Guest("Zapater_aurelie@hotmail.fr",
          List("F"),
          "love-birthday-tente-gold-francois"),
    Guest("david.foisnon@hotmail.fr",
          List("B"),
          "gold-party-king-tente-banana"),
    Guest("solo.natuka@gmail.com",
      List("F"),
      "banana-tiphanie-love-francois-party"),
    Guest("matgilbert@hotmail.fr",
      List("F"),
      "fun-gold-queen-party-francois"),
    Guest("clarisse.loiseau1@gmail.com",
      List("T"),
      "party-tiphanie-banana-birthday-love"),

    //Tokens not yet distributed
    // "party-birthday-bene-love-gold"
    // "tiphanie-birthday-francois-banana-chocolat"
    // "queen-chocolat-banana-bene-party"
    // "birthday-love-francois-chocolat-fun"
  )

  val emails: Set[String] =
    guests.filter(_.token != defaultToken).map { _.name }.toSet
  assert((guests.size - 1) == emails.size)
  val tokens: Set[String] = guests.map { _.token }.toSet
  assert(guests.size == tokens.size)

  //val words = List("tiphanie", "bene", "francois", "penis", "boobs", "fuck", "love", "shit", "sheet", "fun", "dog", "france", "baguette", "god", "dad", "mom", "ass", "fat", "birthday", "chocolat", "trump", "banana", "tente", "old")
  //List.fill(100)(List.fill(5)(words(util.Random.nextInt(words.length))).mkString("-"))

}
