package anniversaire.resources
import Guest._

object Guests {
  val listGuests: List[Guest] = List(
    Guest("tiphdousList@gmail.com", List("T"), "france-france-sheet-shit-france"),
    Guest("glescornet@gmail.com", List("T", "B"), "love-birthday-tiphanie-sheet-god"),
    Guest("Claire.hery@hotmail.fr", List("T", "B"), "fun-mom-god-dad-bene"),
    Guest("sml.vgr@gmail.com", List("T", "B"), "dad-penis-penis-banana-fat"),
    Guest("quentinburban@laposte.net", List("T", "B"), "ass-france-boobs-dad-tiphanie"),
    Guest("marionmetivier86@gmail.com", List("T", "B"), "penis-tente-shit-chocolat-fun"),
    Guest("freslon.julien@gmail.com", List("T", "B"), "sheet-banana-penis-fun-birthday"),
    Guest("lucie86moreau@live.fr", List("T", "B"), "tente-sheet-ass-dog-old"),
    Guest("Germain.marie@live.fr", List("T", "B"), "fun-love-old-baguette-fun"),
    Guest("Clemensbuschhoff@gmail.com", List("T", "B"), "fun-penis-trump-trump-baguette"),
    Guest("mattattoo79@yahoo.de", List("T", "B"), "fuck-francois-banana-tente-france"),
    Guest("kris.neugebauer@googlemail.com", List("T", "B"), "love-fuck-old-bene-chocolat"),
    Guest("laure.chabrolle@gmail.com", List("T", "B"), "birthday-god-sheet-fat-dog"),
    Guest("lamberti.julien@gmail.com", List("T", "B"), "banana-tente-francois-dog-tente"),
    Guest("theotime.tetu@gmail.com", List("T", "B"), "god-francois-mom-mom-france"),
    Guest("Elodie.thines@gmail.com", List("T", "B"), "shit-ass-sheet-dad-tiphanie"),
    Guest("caro_chevalier@hotmail.fr", List("F"), "tente-god-fun-francois-bene"),
    Guest("Gwenaelle.jolygj@gmail.com", List("F"), "shit-ass-dad-bene-banana"),
    Guest("Quentin.fabulet@gmail.com", List("F"), "baguette-love-love-fat-penis"),
    Guest("juliette.laurence@gmail.com", List("F"), "love-baguette-banana-mom-mom"),
    Guest("hug.burban@gmail.com", List("F"), "love-penis-bene-dad-dad"),
    Guest("emelineperrocheau@gmail.com", List("F"), "boobs-dog-baguette-love-ass"),
    Guest("noury.remi@gmail.com", List("F"), "tente-mom-tente-baguette-banana"),
    Guest("boulanger.juli@gmail.com", List("F"), "fuck-francois-dog-mom-tiphanie"),
    Guest("felixdietze@gmail.com", List("F"), "mom-dog-trump-banana-dog"),
    Guest("Quentin.dumont59@gmail.com", List("B", "F"), "tente-fuck-mom-dad-trump"),
    Guest("mgx.barbier@gmail.com", List("B", "F"), "francois-ass-tiphanie-trump-bene"),
    Guest("guillaume.axel.francois@hotmail.com", List("B", "F"), "tiphanie-ass-fun-ass-tente"),
    Guest("raphael.colleau@gmail.com", List("B", "F"), "tente-fuck-mom-chocolat-mom"),
    Guest("creff.arthur@gmail.com", List("B", "F"), "baguette-banana-love-penis-chocolat"),
    Guest("noelie.merlet@hotmail.fr", List("B", "F"), "banana-dog-boobs-fat-trump"),
    Guest("martins.manon@gmail.com", List("B", "F"), "chocolat-boobs-france-birthday-mom"),
    Guest("sandra.vagao@gmail.com", List("B", "F"), "penis-tente-penis-birthday-boobs"),
    Guest("Heygreg@hotmail.fr", List("B", "F"), "fuck-bene-francois-chocolat-france"),
    Guest("clemenceboisdron@gmail.com", List("T", "F"), "ass-birthday-love-francois-fuck"),
    Guest("maxim100@hotmail.fr", List("T", "F"), "fun-god-dog-trump-francois"),
    Guest("Maiw.cadoret@gmail.com", List("T", "F"), "old-banana-god-love-dog"),
    Guest("alexraud@hotmail.com", List("T", "F"), "mom-bene-fuck-shit-france"),
    Guest("lindsay.kibuey@gmail.com", List("T", "F"), "shit-trump-ass-sheet-banana"),
    Guest("rousselot.marie@orange.fr", List("T", "F"), "fun-love-dog-banana-francois"),
    Guest("yannick.richard@hotmail.fr", List("T", "F"), "penis-banana-mom-france-bene"),
    Guest("Lea.reyx@yahoo.fr", List("T", "F"), "banana-god-banana-banana-sheet"),
    Guest("anais.rbt@gmail.com", List("T", "F"), "old-trump-boobs-fuck-birthday"),
    Guest("Theophile.moreau@gmail.com", List("T", "F"), "bene-tiphanie-love-shit-mom"),
    Guest("anais73@gmail.com", List("T", "F"), "love-fat-dad-fun-sheet"),
    Guest("choutet.isabelle@gmail.com", List("T", "F"), "banana-dad-sheet-francois-old"),
    Guest("francois.sail@gmail.com", List("T", "F"), "dog-dog-penis-chocolat-fat"),
    Guest("boris.beillevaire@gmail.com", List("T", "F"), "banana-francois-sheet-fun-trump"),
    Guest("sarah.beauvais@protonmail.com", List("T", "F"), "francois-boobs-fun-ass-baguette"),
    Guest("Matthiasrock@hotmail.fr", List("T", "F"), "old-dog-ass-old-baguette"),
    Guest("aureliaguil@gmail.com", List("T", "F"), "francois-chocolat-shit-dog-fuck"),
    Guest("Florence.gourdon@gmail.com", List("B", "F", "T"), "francois-old-fun-shit-france"),
    Guest("delphine.stabler@gmail.com", List("B", "F", "T"), "boobs-mom-dog-ass-mom"),
    Guest("Sayemoon@free.fr", List("B"), "dog-fun-god-dad-sheet"),
    Guest("carole.legall89@gmail.com", List("B", "F", "T"), "mom-ass-fat-birthday-shit"),
    Guest("stefano1.olivieri@gmail.com", List("B", "F", "T"), "boobs-trump-mom-fat-love"),
    Guest("maxime.ezequel@laposte.net", List("B", "F", "T"), "dad-baguette-fuck-ass-trump"),
    Guest("gourdon_denis@yahoo.fr", List("B", "F", "T"), "francois-old-penis-birthday-tiphanie"),
    Guest("sevmarion@hotmail.com", List("B", "F", "T"), "old-shit-shit-mom-penis"),
    Guest("ronan.laurans@laposte.net", List("B", "F", "T"), "dad-trump-fuck-baguette-mom"),
    Guest("guerinlouise44@gmail.com", List("B", "F", "T"), "francois-sheet-francois-mom-banana"),
    Guest("juliennaud@me.com", List("B", "F", "T"), "baguette-fuck-bene-sheet-tiphanie"),
    Guest("valentineheraud@hotmail.fr", List("B", "F", "T"), "fat-love-tente-chocolat-boobs"),
    Guest("gfrancois.mail@gmail.com", List("B", "F", "T"), "tiphanie-birthday-boobs-tiphanie-tiphanie"),
    Guest("jjliguori@gmail.com", List("B", "F", "T"), "baguette-shit-tiphanie-mom-bene"),
    Guest("marioncle@hotmail.fr", List("B", "F", "T"), "penis-sheet-francois-god-ass"),
    Guest("hugo.langlaisvignon@gmail.com", List("B", "F", "T"), "fuck-love-ass-tente-tente"),
    Guest("sebastien.decreme@gmail.com", List("B", "F", "T"), "chocolat-francois-sheet-dad-tente"),
    Guest("marie.rpch@gmail.com", List("B", "F", "T"), "boobs-sheet-mom-tente-fuck"),
    Guest("joel.mballa@gmail.com", List("B", "F", "T"), "boobs-god-old-fuck-tente"),
    Guest("fabian-braun@mailbox.org", List("B", "F", "T"), "boobs-god-francois-fat-dad"),
    Guest("margaux.peneau@gmail.com", List("B", "F", "T"), "tiphanie-trump-shit-god-tente"),
    Guest("Florent.creutin@gmail.com", List("B", "F", "T"), "mom-mom-francois-shit-banana"),
    Guest("didi.el.zein@gmail.com", List("B", "F", "T"), "trump-mom-francois-god-fun"),
    Guest("mathias.peronne@gmail.com", List("B", "F", "T"), "mom-boobs-boobs-fat-tiphanie"),
    Guest("champion.sophie@yahoo.com", List("B", "F", "T"), "tiphanie-tente-penis-birthday-francois"),
    Guest("laulotte44@hotmail.com", List("B", "F", "T"), "fun-dog-shit-tente-old"),
    Guest("Michel-lebourdonnec@live.fr", List("B", "F", "T"), "birthday-shit-love-dad-love"),
    Guest("belliniloris1@gmail.com", List("B", "F", "T"), "dad-sheet-god-old-boobs"),
    Guest("youri.corbineau@gmail.com", List("B", "F", "T"), "god-banana-shit-birthday-dad"),
    Guest("florent.quilichini@gmail.com", List("B", "F", "T"), "bene-boobs-trump-dog-trump"),
    Guest("aurelierolland@hotmail.fr", List("B", "F", "T"), "old-shit-francois-tente-trump"),
    Guest("Guillaume.chopin@neuf.fr", List("B", "F", "T"), "sheet-god-birthday-banana-love"),
    Guest("hamon.matthieu@gmail.com", List("B", "F", "T"), "old-shit-shit-fuck-boobs"),
    Guest("dimitri.fasquel@free.fr", List("B", "F", "T"), "fun-fuck-ass-france-france"),
    Guest("letellier.avocat@laposte.net", List("B", "F", "T"), "penis-dog-god-baguette-penis"),
    Guest("gregoireroux69@gmail.com", List("B", "F", "T"), "fat-god-chocolat-france-sheet"),
    Guest("jeanromainsignorelli@gmail.com", List("B", "F", "T"), "bene-tiphanie-sheet-sheet-mom"),
    Guest("lolaalfonzo@gmail.com", List("B", "F", "T"), "tiphanie-trump-birthday-chocolat-trump")
  )

//val words = List("tiphanie", "bene", "francois", "penis", "boobs", "fuck", "love", "shit", "sheet", "fun", "dog", "france", "baguette", "god", "dad", "mom", "ass", "fat", "birthday", "chocolat", "trump", "banana", "tente", "old")
//List.fill(100)(List.fill(5)(words(util.Random.nextInt(words.length))).mkString("-"))

}
