package anniversaire

object Costumes {
  val costumesList: List[(String, String)] = List(
    ("Mario", "Luigi"),
    ("Astérix", "Obélix"),
    ("Roméo", "Juliette"),
    ("Ariel", "Polochon"),
    ("Tintin", "milou"),
    ("Dupont", "Dupont"),
    ("Winnie", "Porcinet"),
    ("Sherlock", "Watson"),
    ("Dr Jekyll", "Mr Hyde"),
    ("Robinson", "Vendredi"),
    ("Princesse Leïa", "Han Solo"),
    ("Laurel", "Hardy"),
    ("Bonnie", "Clyde"),
    ("G. de Montmirail", "Jacquouille la Fripouille"),
    ("Tom", "Jerry"),
    ("Cléopatre", "César"),
    ("Batman", "Robin"),
    ("Père Noel", "mère Noël"),
    ("Mr Smith", "Mrs Smith"),
    ("Leelou Dallas", "Corben Dallas"),
    ("Marge", "Homer Simpson"),
    ("Olive", "Tom"),
    ("Jeanne", "Serge"),
    ("Les soeurs", "Williams"),
    ("Trump", "Melania"),
    ("Aladdin", "Abu"),
    ("Titi", "Gros minet"),
    ("Adam", "Eve"),
    ("Jesus", "Marie"),
    ("Les frères", "Bogdanov"),
    ("Bébé", "Johnny (dirty dancing)"),
    ("Vincent Vega (Pulp fiction)", "Jules Winnfield (Pulp fiction)"),
    ("Jack (titanic)", "rose (titanic)"),
    ("austin power", "la copine de Austin power"),
    ("shrek", "la princesse de Shrek"),
    ("sartre", "beauvoir"),
    ("popeye", "la femme de popeye"),
    ("superman", "superwoman"),
    ("118", "218"),
    ("petit chaperon rouge", "le loup"),
    ("cruella", "un dalmatien"),
    ("ou est charlie", "sa charlène"),
    ("ketchup", "mayo"),
    ("le bossu", "esmeralda"),
    ("strumpf", "strumpfette"),
    ("danny zuko(grease)", "sandy olsson (grease)"),
    ("thelma", "louise"),
    ("Harry Potter", "Hermione Granger"),
    ("Mitch", "Pamela (alerte à malibu)"),
    ("Tomtom", "Nana"),
    ("Mickey", "Mini"),
    ("Veronique", "Davina"),
    ("Ange", "démon"),
    ("M&ms bleu", "M&ms rouge"),
    ("Lenon", "mccartney"),
    ("César", "Brutus"),
    ("Famille Addams", "Famille Adamas")
  )

}
